[package]
name = "rststuff"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["lib/basic_echo_server"]

[dependencies]
basic_echo_server = { path = "lib/basic_echo_server" }
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["full"] }
serde = "1.0.210"
serde_json = "1.0.128"
