[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "lib/add",
    "lib/sub"
]

[dependencies]
add = { path = "lib/add" }
rand = "0.8.5"
sub = { path = "lib/sub" }

